// AUTO-GENERATED by scripts/generate-templates.mjs — do not edit by hand.
// Edit the specs in that script and re-run it; commit the PDFs alongside.
import type { TemplateDef } from "./types";

export const generatedTemplates: TemplateDef[] = [
  {
    "id": "listing_agreement",
    "name": "Exclusive Right to Sell Listing Agreement",
    "shortName": "Listing",
    "description": "Appoints the brokerage as the seller's exclusive listing agent — price, term, and commission.",
    "category": "Listings & transactions",
    "kind": "acroform",
    "file": "templates/listing-agreement.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "propertyAddress",
        "label": "Property address",
        "type": "text",
        "required": true,
        "hint": "Full street address, town, state."
      },
      {
        "key": "sellerName",
        "label": "Seller(s)",
        "type": "text",
        "required": true
      },
      {
        "key": "sellerPhone",
        "label": "Seller phone",
        "type": "text"
      },
      {
        "key": "listPrice",
        "label": "List price ($)",
        "type": "currency",
        "required": true
      },
      {
        "key": "commissionPercent",
        "label": "Commission (%)",
        "type": "percent",
        "required": true
      },
      {
        "key": "coopCommission",
        "label": "Co-broke share (%)",
        "type": "percent",
        "hint": "Portion offered to a cooperating buyer's broker."
      },
      {
        "key": "startDate",
        "label": "Listing start",
        "type": "date",
        "required": true
      },
      {
        "key": "endDate",
        "label": "Listing end",
        "type": "date",
        "required": true
      },
      {
        "key": "exclusions",
        "label": "Exclusions / special terms (optional)",
        "type": "longtext",
        "hint": "Items excluded from the sale or special listing terms."
      },
      {
        "key": "brokerageFirm",
        "label": "Brokerage firm",
        "type": "text",
        "source": "broker_agency_name"
      },
      {
        "key": "agentName",
        "label": "Agent",
        "type": "text",
        "source": "agent_name"
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "general_addendum",
    "name": "Addendum / Amendment to Contract",
    "shortName": "Addendum",
    "description": "Adds or amends terms on an existing contract — all other terms stay in force.",
    "category": "Listings & transactions",
    "kind": "acroform",
    "file": "templates/general-addendum.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "propertyAddress",
        "label": "Property address",
        "type": "text",
        "required": true,
        "hint": "Full street address, town, state."
      },
      {
        "key": "contractDate",
        "label": "Contract dated",
        "type": "date",
        "required": true
      },
      {
        "key": "sellerName",
        "label": "Seller(s)",
        "type": "text",
        "required": true
      },
      {
        "key": "buyerName",
        "label": "Buyer(s)",
        "type": "text",
        "required": true
      },
      {
        "key": "terms",
        "label": "The parties agree as follows",
        "type": "longtext",
        "required": true,
        "hint": "The new or amended terms, in plain language."
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "escalation_addendum",
    "name": "Escalation Clause Addendum",
    "shortName": "Escalation",
    "description": "Automatically escalates the buyer's offer over competing bona fide offers, up to a cap.",
    "category": "Listings & transactions",
    "kind": "acroform",
    "file": "templates/escalation-addendum.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "propertyAddress",
        "label": "Property address",
        "type": "text",
        "required": true,
        "hint": "Full street address, town, state."
      },
      {
        "key": "buyerName",
        "label": "Buyer(s)",
        "type": "text",
        "required": true
      },
      {
        "key": "sellerName",
        "label": "Seller(s)",
        "type": "text"
      },
      {
        "key": "baseOfferPrice",
        "label": "Base offer price ($)",
        "type": "currency",
        "required": true
      },
      {
        "key": "escalationIncrement",
        "label": "Escalation increment ($)",
        "type": "currency",
        "required": true
      },
      {
        "key": "maxPrice",
        "label": "Maximum price ($)",
        "type": "currency",
        "required": true
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "mutual_release",
    "name": "Mutual Release & Termination",
    "shortName": "Release",
    "description": "Terminates a contract by mutual agreement and directs the deposit.",
    "category": "Listings & transactions",
    "kind": "acroform",
    "file": "templates/mutual-release.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "propertyAddress",
        "label": "Property address",
        "type": "text",
        "required": true,
        "hint": "Full street address, town, state."
      },
      {
        "key": "contractDate",
        "label": "Contract dated",
        "type": "date",
        "required": true
      },
      {
        "key": "buyerName",
        "label": "Buyer(s)",
        "type": "text",
        "required": true
      },
      {
        "key": "sellerName",
        "label": "Seller(s)",
        "type": "text",
        "required": true
      },
      {
        "key": "depositDisposition",
        "label": "Earnest money deposit shall be released to",
        "type": "text",
        "required": true,
        "hint": "Who receives the deposit, and how it is split if shared."
      },
      {
        "key": "releaseTerms",
        "label": "Additional terms (optional)",
        "type": "longtext"
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "deposit_receipt",
    "name": "Earnest Money Deposit Receipt",
    "shortName": "Deposit receipt",
    "description": "Acknowledges receipt of a buyer's earnest money deposit and where it's held.",
    "category": "Listings & transactions",
    "kind": "acroform",
    "file": "templates/deposit-receipt.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "propertyAddress",
        "label": "Property address",
        "type": "text",
        "required": true,
        "hint": "Full street address, town, state."
      },
      {
        "key": "buyerName",
        "label": "Received from (buyer)",
        "type": "text",
        "required": true
      },
      {
        "key": "contractDate",
        "label": "Contract dated",
        "type": "date"
      },
      {
        "key": "depositAmount",
        "label": "Amount received ($)",
        "type": "currency",
        "required": true
      },
      {
        "key": "paymentMethod",
        "label": "Form of payment",
        "type": "text",
        "hint": "Check, wire, or ACH."
      },
      {
        "key": "receivedDate",
        "label": "Date received",
        "type": "date",
        "required": true
      },
      {
        "key": "escrowHolder",
        "label": "Held in escrow by",
        "type": "text",
        "required": true,
        "hint": "Escrow agent, brokerage, or attorney holding the funds."
      },
      {
        "key": "brokerageFirm",
        "label": "Brokerage firm",
        "type": "text",
        "source": "broker_agency_name"
      },
      {
        "key": "agentName",
        "label": "Agent",
        "type": "text",
        "source": "agent_name"
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "referral_agreement",
    "name": "Referral Fee Agreement",
    "shortName": "Referral",
    "description": "Broker-to-broker referral — who's referred, who pays, and the fee.",
    "category": "Brokerage & office",
    "kind": "acroform",
    "file": "templates/referral-agreement.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "referringBrokerage",
        "label": "Referring brokerage",
        "type": "text",
        "required": true
      },
      {
        "key": "referringAgent",
        "label": "Referring agent",
        "type": "text",
        "required": true
      },
      {
        "key": "receivingBrokerage",
        "label": "Receiving brokerage",
        "type": "text",
        "required": true,
        "hint": "Often your own brokerage."
      },
      {
        "key": "receivingAgent",
        "label": "Receiving agent",
        "type": "text"
      },
      {
        "key": "clientName",
        "label": "Referred client",
        "type": "text",
        "required": true
      },
      {
        "key": "propertyOrArea",
        "label": "Property / market area",
        "type": "text"
      },
      {
        "key": "referralFeePercent",
        "label": "Referral fee (%)",
        "type": "percent",
        "required": true,
        "hint": "Percent of the receiving side's gross commission."
      },
      {
        "key": "payableTerms",
        "label": "Payable",
        "type": "text",
        "hint": "E.g. at closing, from the receiving side's gross commission."
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "commission_disbursement",
    "name": "Commission Disbursement Authorization",
    "shortName": "CDA",
    "description": "Instructs the closing agent how to pay out the brokerage's commission (CDA).",
    "category": "Brokerage & office",
    "kind": "acroform",
    "file": "templates/commission-disbursement.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "propertyAddress",
        "label": "Property address",
        "type": "text",
        "required": true,
        "hint": "Full street address, town, state."
      },
      {
        "key": "closingDate",
        "label": "Closing date",
        "type": "date",
        "required": true
      },
      {
        "key": "salesPrice",
        "label": "Sales price ($)",
        "type": "currency",
        "required": true
      },
      {
        "key": "buyerName",
        "label": "Buyer(s)",
        "type": "text"
      },
      {
        "key": "sellerName",
        "label": "Seller(s)",
        "type": "text"
      },
      {
        "key": "grossCommission",
        "label": "Gross commission ($)",
        "type": "currency",
        "required": true
      },
      {
        "key": "agentSplit",
        "label": "Agent split",
        "type": "text",
        "hint": "E.g. 70/30."
      },
      {
        "key": "transactionFee",
        "label": "Transaction fee ($)",
        "type": "currency"
      },
      {
        "key": "agentPayout",
        "label": "Pay to agent ($)",
        "type": "currency",
        "required": true
      },
      {
        "key": "payableTo",
        "label": "Agent payee name",
        "type": "text",
        "required": true,
        "hint": "Exactly as the check/wire should read."
      },
      {
        "key": "disburseBy",
        "label": "Closing agent (attorney / title / escrow)",
        "type": "text",
        "required": true
      },
      {
        "key": "deliveryInstructions",
        "label": "Delivery instructions (optional)",
        "type": "longtext",
        "hint": "Wire per instructions on file, mail, pickup…"
      },
      {
        "key": "brokerageFirm",
        "label": "Brokerage firm",
        "type": "text",
        "source": "broker_agency_name"
      },
      {
        "key": "authorizedBy",
        "label": "Authorized by",
        "type": "text",
        "source": "agent_name"
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "independent_contractor",
    "name": "Independent Contractor Agreement",
    "shortName": "Contractor (ICA)",
    "description": "Short-form broker–salesperson agreement: status, split, and termination.",
    "category": "Brokerage & office",
    "kind": "acroform",
    "file": "templates/independent-contractor.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "brokerageFirm",
        "label": "Brokerage firm",
        "type": "text",
        "required": true,
        "source": "broker_agency_name"
      },
      {
        "key": "contractorName",
        "label": "Salesperson",
        "type": "text",
        "required": true
      },
      {
        "key": "licenseNumber",
        "label": "License #",
        "type": "text"
      },
      {
        "key": "commissionSplit",
        "label": "Commission split",
        "type": "text",
        "required": true,
        "hint": "E.g. 70/30 (salesperson/brokerage)."
      },
      {
        "key": "transactionFee",
        "label": "Transaction fee ($)",
        "type": "currency"
      },
      {
        "key": "startDate",
        "label": "Start date",
        "type": "date",
        "required": true
      },
      {
        "key": "termNotes",
        "label": "Additional terms (optional)",
        "type": "longtext"
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "lead_paint_disclosure",
    "name": "Lead-Based Paint Disclosure",
    "shortName": "Lead paint",
    "description": "Federal lead-based paint disclosure for pre-1978 housing sales.",
    "category": "Leasing & compliance",
    "kind": "acroform",
    "file": "templates/lead-paint-disclosure.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "propertyAddress",
        "label": "Property address",
        "type": "text",
        "required": true,
        "hint": "Full street address, town, state."
      },
      {
        "key": "leadKnown",
        "label": "Known lead-based paint present",
        "type": "checkbox",
        "hint": "Check if the seller knows of lead-based paint or hazards; explain below."
      },
      {
        "key": "leadKnownDetails",
        "label": "Known lead-based paint / hazards (if any)",
        "type": "longtext"
      },
      {
        "key": "noLeadKnowledge",
        "label": "No knowledge of lead-based paint",
        "type": "checkbox",
        "hint": "Check if the seller has no knowledge of lead-based paint or hazards."
      },
      {
        "key": "recordsProvided",
        "label": "Records provided",
        "type": "checkbox",
        "hint": "Check if reports/records were provided; list below."
      },
      {
        "key": "recordsList",
        "label": "Records / reports provided (if any)",
        "type": "longtext"
      },
      {
        "key": "noRecords",
        "label": "No records or reports",
        "type": "checkbox",
        "hint": "Check if the seller has no reports or records."
      },
      {
        "key": "pamphletReceived",
        "label": "EPA pamphlet received",
        "type": "checkbox"
      },
      {
        "key": "inspectionOpportunity",
        "label": "10-day inspection opportunity",
        "type": "checkbox"
      },
      {
        "key": "inspectionWaived",
        "label": "Inspection waived",
        "type": "checkbox"
      },
      {
        "key": "sellerName",
        "label": "Seller(s)",
        "type": "text",
        "required": true
      },
      {
        "key": "buyerName",
        "label": "Buyer(s)",
        "type": "text",
        "required": true
      },
      {
        "key": "agentName",
        "label": "Agent",
        "type": "text",
        "source": "agent_name"
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  },
  {
    "id": "rental_application",
    "name": "Rental Application",
    "shortName": "Rental app",
    "description": "Tenant application: contact, income, references, and screening consent.",
    "category": "Leasing & compliance",
    "kind": "acroform",
    "file": "templates/rental-application.pdf",
    "pages": 1,
    "fields": [
      {
        "key": "propertyAddress",
        "label": "Property applying for",
        "type": "text",
        "required": true,
        "hint": "Full street address, town, state."
      },
      {
        "key": "applicantName",
        "label": "Applicant name",
        "type": "text",
        "required": true
      },
      {
        "key": "applicantPhone",
        "label": "Phone",
        "type": "text",
        "required": true
      },
      {
        "key": "applicantEmail",
        "label": "Email",
        "type": "text"
      },
      {
        "key": "moveInDate",
        "label": "Desired move-in",
        "type": "date",
        "required": true
      },
      {
        "key": "currentAddress",
        "label": "Current address",
        "type": "text",
        "required": true
      },
      {
        "key": "employer",
        "label": "Employer",
        "type": "text"
      },
      {
        "key": "position",
        "label": "Position",
        "type": "text"
      },
      {
        "key": "monthlyIncome",
        "label": "Monthly income ($)",
        "type": "currency"
      },
      {
        "key": "landlordRef",
        "label": "Current landlord (name & phone)",
        "type": "text"
      },
      {
        "key": "occupants",
        "label": "All occupants (names / ages)",
        "type": "text"
      },
      {
        "key": "pets",
        "label": "Pets (type / number)",
        "type": "text"
      },
      {
        "key": "creditConsent",
        "label": "Screening consent",
        "type": "checkbox",
        "required": true,
        "hint": "Applicant must consent to credit/background screening."
      },
      {
        "key": "date",
        "label": "Date",
        "type": "date",
        "required": true
      }
    ],
    "placements": {}
  }
] as TemplateDef[];
