import type { TemplateDef } from "./types";

// SmartMLS residential purchase agreement (CT), 2 pages. Fields are listed in
// strict DOCUMENT ORDER — the voice walkthrough asks them top to bottom, like
// reading down the page. Coordinates in PDF points (612x792, y from bottom),
// anchored against pdftotext -bbox word positions.
export const purchase: TemplateDef = {
  id: "purchase",
  category: "Listings & transactions",
  name: "Purchase Agreement",
  shortName: "Purchase",
  description: "SmartMLS residential purchase agreement (Connecticut).",
  file: "templates/purchase.pdf",
  pages: 2,
  fields: [
    // ---- Page 1 ----
    { key: "date", label: "Agreement date", type: "date", required: true },
    { key: "sellerName", label: "Seller", type: "text", required: true },
    { key: "sellerAddress", label: "Seller residing at", type: "text" },
    { key: "buyerName", label: "Buyer", type: "text", required: true },
    { key: "buyerAddress", label: "Buyer residing at", type: "text" },
    {
      key: "propertyDescription",
      label: "Property known and described as",
      type: "longtext",
      required: true,
    },
    { key: "includingItems", label: "Including the following extra items", type: "text" },
    { key: "excludingItems", label: "Excluding the following items", type: "text" },
    { key: "price", label: "Price ($)", type: "currency", required: true },
    { key: "binderAmount", label: "Cash as a binder herewith ($)", type: "currency" },
    { key: "escrowAgent", label: "Binder held in escrow by", type: "text" },
    { key: "supersedingAmount", label: "Cash on signing superseding contract ($)", type: "currency" },
    { key: "closingAmount", label: "Cash on taking title ($)", type: "currency" },
    { key: "closingDate", label: "Closing date", type: "date" },
    { key: "mortgageAmount", label: "New mortgage amount ($)", type: "currency" },
    {
      key: "saleContingent",
      label: "Sale IS contingent on financing",
      type: "checkbox",
      hint: "Check if the sale depends on the buyer obtaining financing. If not, check 'Sale is NOT contingent' instead.",
      pairedWith: ["saleNotContingent"],
    },
    {
      key: "saleNotContingent",
      label: "Sale is NOT contingent on financing",
      type: "checkbox",
      hint: "Check if the sale does not depend on financing.",
      pairedWith: ["saleContingent"],
    },
    { key: "financingDate", label: "Financing to be obtained by (date)", type: "date" },
    { key: "mortgageYears", label: "Mortgage term (# of years)", type: "text" },
    {
      key: "contingencies",
      label: "Contingencies",
      type: "longtext",
      hint: "Inspections, appraisal, sale of buyer's home, addenda, or any other conditions — or '-' if none.",
    },
    // ---- Page 2 ----
    {
      key: "disclosureFurnished",
      label: "Property Condition Disclosure HAS been furnished",
      type: "checkbox",
      hint: "Check if the seller furnished the disclosure form. If not, check 'has NOT been furnished' instead ($500 credit applies).",
      pairedWith: ["disclosureNotFurnished"],
    },
    {
      key: "disclosureNotFurnished",
      label: "Property Condition Disclosure has NOT been furnished",
      type: "checkbox",
      hint: "Check if the disclosure was not furnished — buyer receives a $500 credit at closing.",
      pairedWith: ["disclosureFurnished"],
    },
    { key: "contractSignBy", label: "Superseding contract to be signed on or before", type: "date" },
    { key: "brokerFeeAmount", label: "Buyer's broker fee ($, alternative to %)", type: "currency", pairedWith: ["brokerFeePercent"] },
    { key: "brokerFeePercent", label: "Buyer's broker fee (% of contract price)", type: "percent", pairedWith: ["brokerFeeAmount"] },
    {
      key: "dualAgent",
      label: "Listing agent is acting as a Dual Agent",
      type: "checkbox",
      pairedWith: ["sellingAgentBuyersAgent", "authorizedSubAgent"],
    },
    {
      key: "sellingAgentBuyersAgent",
      label: "Selling agent is Buyer's Agent",
      type: "checkbox",
      pairedWith: ["dualAgent", "authorizedSubAgent"],
    },
    {
      key: "authorizedSubAgent",
      label: "Authorized Sub-Agent",
      type: "checkbox",
      pairedWith: ["dualAgent", "sellingAgentBuyersAgent"],
    },
    { key: "sellerAgentName", label: "Seller's agent name", type: "text" },
    { key: "sellerAgentPhone", label: "Seller's agent phone", type: "text" },
    { key: "sellerAgentLicense", label: "Seller's agent license #", type: "text" },
    { key: "sellerAgentFirm", label: "Seller's agent firm", type: "text" },
    { key: "sellerAgentAddress", label: "Seller's agent address", type: "text" },
    // Auto-filled from the agent profile (buyer's agent block):
    { key: "buyerAgentName", label: "Buyer's agent name", type: "text", source: "agent_name" },
    { key: "buyerAgentPhone", label: "Buyer's agent phone", type: "text", source: "phone" },
    { key: "buyerAgentLicense", label: "Buyer's agent license #", type: "text", source: "license_number" },
    { key: "buyerAgentFirm", label: "Buyer's agent firm", type: "text", source: "broker_agency_name" },
    { key: "buyerAgentAddress", label: "Buyer's agent address", type: "text", source: "street" },
    { key: "sellerAttorneyName", label: "Seller's attorney name", type: "text" },
    { key: "sellerAttorneyPhone", label: "Seller's attorney phone", type: "text" },
    { key: "sellerAttorneyEmail", label: "Seller's attorney email", type: "text" },
    { key: "sellerAttorneyAddress", label: "Seller's attorney address", type: "text" },
    { key: "buyerAttorneyName", label: "Buyer's attorney name", type: "text" },
    { key: "buyerAttorneyPhone", label: "Buyer's attorney phone", type: "text" },
    { key: "buyerAttorneyEmail", label: "Buyer's attorney email", type: "text" },
    { key: "buyerAttorneyAddress", label: "Buyer's attorney address", type: "text" },
    { key: "acceptanceDate", label: "Acceptance date", type: "date" },
  ],
  placements: {
    // Page 0
    date: { page: 0, x: 479, y: 715, size: 10, maxWidth: 120 },
    sellerName: { page: 0, x: 170, y: 693, size: 10, maxWidth: 280 },
    sellerAddress: { page: 0, x: 110, y: 672, size: 9, maxWidth: 320 },
    buyerName: { page: 0, x: 82, y: 651, size: 10, maxWidth: 350 },
    buyerAddress: { page: 0, x: 110, y: 628, size: 9, maxWidth: 330 },
    propertyDescription: { page: 0, x: 200, y: 607, size: 9, maxWidth: 375 },
    includingItems: { page: 0, x: 200, y: 542, size: 9, maxWidth: 375 },
    excludingItems: { page: 0, x: 200, y: 477, size: 9, maxWidth: 375 },
    price: { page: 0, x: 105, y: 343, size: 10, maxWidth: 120 },
    binderAmount: { page: 0, x: 118, y: 321, size: 9, maxWidth: 95 },
    escrowAgent: { page: 0, x: 315, y: 300, size: 9, maxWidth: 250 },
    supersedingAmount: { page: 0, x: 118, y: 278, size: 9, maxWidth: 95 },
    closingAmount: { page: 0, x: 118, y: 256, size: 9, maxWidth: 95 },
    closingDate: { page: 0, x: 378, y: 256, size: 9, maxWidth: 120 },
    mortgageAmount: { page: 0, x: 118, y: 235, size: 9, maxWidth: 95 },
    saleContingent: { page: 0, x: 282.5, y: 214, size: 9 },
    saleNotContingent: { page: 0, x: 371.5, y: 214, size: 9 },
    financingDate: { page: 0, x: 402, y: 192, size: 9, maxWidth: 60 },
    mortgageYears: { page: 0, x: 302, y: 170, size: 9, maxWidth: 65 },
    contingencies: { page: 0, x: 100, y: 104, size: 9, maxWidth: 470 },
    // Page 1
    disclosureFurnished: { page: 1, x: 216, y: 747, size: 8 },
    disclosureNotFurnished: { page: 1, x: 266, y: 747, size: 8 },
    contractSignBy: { page: 1, x: 216, y: 652, size: 8, maxWidth: 56 },
    brokerFeeAmount: { page: 1, x: 342, y: 576, size: 9, maxWidth: 90 },
    brokerFeePercent: { page: 1, x: 446, y: 576, size: 9, maxWidth: 28 },
    dualAgent: { page: 1, x: 262, y: 436, size: 9 },
    sellingAgentBuyersAgent: { page: 1, x: 409.5, y: 436, size: 9 },
    authorizedSubAgent: { page: 1, x: 528, y: 436, size: 9 },
    sellerAgentName: { page: 1, x: 98, y: 407, size: 9, maxWidth: 140 },
    sellerAgentPhone: { page: 1, x: 244, y: 407, size: 9, maxWidth: 58 },
    sellerAgentLicense: { page: 1, x: 108, y: 381, size: 9, maxWidth: 190 },
    sellerAgentFirm: { page: 1, x: 93, y: 353, size: 9, maxWidth: 210 },
    sellerAgentAddress: { page: 1, x: 76, y: 325, size: 9, maxWidth: 225 },
    buyerAgentName: { page: 1, x: 411, y: 407, size: 9, maxWidth: 105 },
    buyerAgentPhone: { page: 1, x: 522, y: 407, size: 9, maxWidth: 50 },
    buyerAgentLicense: { page: 1, x: 378, y: 381, size: 9, maxWidth: 190 },
    buyerAgentFirm: { page: 1, x: 363, y: 353, size: 9, maxWidth: 210 },
    buyerAgentAddress: { page: 1, x: 346, y: 325, size: 9, maxWidth: 225 },
    sellerAttorneyName: { page: 1, x: 106, y: 297, size: 9, maxWidth: 135 },
    sellerAttorneyPhone: { page: 1, x: 244, y: 297, size: 9, maxWidth: 58 },
    sellerAttorneyEmail: { page: 1, x: 107, y: 269, size: 9, maxWidth: 190 },
    sellerAttorneyAddress: { page: 1, x: 76, y: 241, size: 9, maxWidth: 225 },
    buyerAttorneyName: { page: 1, x: 377, y: 297, size: 9, maxWidth: 135 },
    buyerAttorneyPhone: { page: 1, x: 514, y: 297, size: 9, maxWidth: 58 },
    buyerAttorneyEmail: { page: 1, x: 377, y: 269, size: 9, maxWidth: 190 },
    buyerAttorneyAddress: { page: 1, x: 346, y: 241, size: 9, maxWidth: 225 },
    acceptanceDate: { page: 1, x: 265, y: 60, size: 9, maxWidth: 150 },
  },
};
