import type { TemplateDef } from "./types";

// Coordinates derived from the source PDF (612x792). y is from bottom-left.
export const purchase: TemplateDef = {
  id: "purchase",
  category: "Listings & transactions",
  name: "Purchase Agreement",
  shortName: "Purchase",
  description: "SmartMLS residential purchase agreement (Connecticut).",
  file: "templates/purchase.pdf",
  pages: 2,
  fields: [
    { key: "date", label: "Agreement date", type: "date", required: true },
    { key: "sellerName", label: "Seller", type: "text", required: true },
    { key: "sellerAddress", label: "Seller residing at", type: "text" },
    { key: "buyerName", label: "Buyer", type: "text", required: true },
    { key: "buyerAddress", label: "Buyer residing at", type: "text" },
    {
      key: "propertyDescription",
      label: "Property known and described as",
      type: "longtext",
      required: true,
    },
    { key: "includingItems", label: "Including extra items", type: "text" },
    { key: "excludingItems", label: "Excluding items", type: "text" },
    { key: "price", label: "Price ($)", type: "currency", required: true },
    { key: "binderAmount", label: "Binder paid with agreement ($)", type: "currency" },
    { key: "escrowAgent", label: "Binder held in escrow by", type: "text" },
    { key: "supersedingAmount", label: "Cash on signing superseding contract ($)", type: "currency" },
    { key: "closingAmount", label: "Cash on taking title ($)", type: "currency" },
    { key: "closingDate", label: "Closing date", type: "date" },
    { key: "mortgageAmount", label: "New mortgage amount ($)", type: "currency" },
    { key: "financingDate", label: "Financing contingency date", type: "date" },
    { key: "mortgageYears", label: "Mortgage term (# of years)", type: "text" },
    { key: "brokerFeeAmount", label: "Broker fee ($, alternative to %)", type: "currency" },
    { key: "brokerFeePercent", label: "Broker fee (% of contract price)", type: "percent" },
    { key: "contractSignBy", label: "Superseding contract to be signed by", type: "date" },
    { key: "acceptanceDate", label: "Acceptance date", type: "date" },
    // Auto-filled from the agent profile (buyer's agent block):
    { key: "buyerAgentName", label: "Buyer's agent name", type: "text", source: "agent_name" },
    { key: "buyerAgentPhone", label: "Buyer's agent phone", type: "text", source: "phone" },
    { key: "buyerAgentLicense", label: "Buyer's agent license #", type: "text", source: "license_number" },
    { key: "buyerAgentFirm", label: "Buyer's agent firm", type: "text", source: "broker_agency_name" },
    { key: "buyerAgentAddress", label: "Buyer's agent address", type: "text", source: "street" },
  ],
  placements: {
    // Page 0
    date: { page: 0, x: 479, y: 715, size: 10, maxWidth: 120 },
    sellerName: { page: 0, x: 170, y: 693, size: 10, maxWidth: 280 },
    sellerAddress: { page: 0, x: 110, y: 672, size: 9, maxWidth: 320 },
    buyerName: { page: 0, x: 82, y: 651, size: 10, maxWidth: 350 },
    buyerAddress: { page: 0, x: 110, y: 628, size: 9, maxWidth: 330 },
    propertyDescription: { page: 0, x: 200, y: 607, size: 9, maxWidth: 375 },
    includingItems: { page: 0, x: 200, y: 542, size: 9, maxWidth: 375 },
    excludingItems: { page: 0, x: 200, y: 477, size: 9, maxWidth: 375 },
    price: { page: 0, x: 105, y: 343, size: 10, maxWidth: 120 },
    binderAmount: { page: 0, x: 118, y: 321, size: 9, maxWidth: 95 },
    escrowAgent: { page: 0, x: 315, y: 300, size: 9, maxWidth: 250 },
    supersedingAmount: { page: 0, x: 118, y: 278, size: 9, maxWidth: 95 },
    closingAmount: { page: 0, x: 118, y: 256, size: 9, maxWidth: 95 },
    closingDate: { page: 0, x: 378, y: 256, size: 9, maxWidth: 120 },
    mortgageAmount: { page: 0, x: 118, y: 235, size: 9, maxWidth: 95 },
    financingDate: { page: 0, x: 402, y: 192, size: 9, maxWidth: 60 },
    mortgageYears: { page: 0, x: 302, y: 170, size: 9, maxWidth: 65 },
    // Page 1
    brokerFeeAmount: { page: 1, x: 342, y: 576, size: 9, maxWidth: 90 },
    brokerFeePercent: { page: 1, x: 446, y: 576, size: 9, maxWidth: 28 },
    contractSignBy: { page: 1, x: 216, y: 652, size: 8, maxWidth: 56 },
    buyerAgentName: { page: 1, x: 411, y: 407, size: 9, maxWidth: 105 },
    buyerAgentPhone: { page: 1, x: 522, y: 407, size: 9, maxWidth: 50 },
    buyerAgentLicense: { page: 1, x: 378, y: 381, size: 9, maxWidth: 190 },
    buyerAgentFirm: { page: 1, x: 363, y: 353, size: 9, maxWidth: 210 },
    buyerAgentAddress: { page: 1, x: 346, y: 325, size: 9, maxWidth: 225 },
    acceptanceDate: { page: 1, x: 265, y: 60, size: 9, maxWidth: 150 },
  },
};
